### ISSUE TITLE
Error about root privilege on Linux

### ISSUE THREAD

**Issue by YuruiHong** [BlockCnFuture/LinuxWechat#1]
```bash
$ npm start

> electron-wechat-web@1.2.0 start
> electron main.js

[0419/172530.977543:FATAL:electron_main_delegate.cc(300)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
<path>/LinuxWechat/src/node_modules/electron/dist/electron exited with signal SIGTRAP
```

**Comment by BlockCnFuture** [comment]
sorry for replay too late. this problem cased by you start electron as root and this project use new electron version.
for security,you should start electron with other account without root privileges.
or you can use older vision electron (v11) to start this project
